[project]
name = "k8s-image-policy-controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "loguru>=0.7.3",
]
